import { supabase } from "@/lib/supabase"

const DEFAULT_CATEGORIES = [
  {
    name: "Vacation 🏖️",
    emoji: null,
    colour: "green",
    leave_type: "paid",
    accrual_method: "fixed",
    amount_value: 20,
    granting_frequency: "hire_anniversary",
    accrual_day: null,
    anniversary_years: null,
    new_hire_rule: "waiting_period",
    waiting_period_value: 3,
    waiting_period_unit: "month",
    carryover_limit_enabled: false,
    carryover_max_days: null,
    carryover_expiration_value: null,
    carryover_expiration_unit: null,
    is_active: true,
    sort_order: 0,
  },
  {
    name: "Sick leave 🤒",
    emoji: null,
    colour: "red",
    leave_type: "paid",
    accrual_method: "fixed",
    amount_value: 10,
    granting_frequency: "hire_anniversary",
    accrual_day: null,
    anniversary_years: null,
    new_hire_rule: "immediate",
    waiting_period_value: null,
    waiting_period_unit: null,
    carryover_limit_enabled: false,
    carryover_max_days: null,
    carryover_expiration_value: null,
    carryover_expiration_unit: null,
    is_active: true,
    sort_order: 1,
  },
  {
    name: "Business trip 💼",
    emoji: null,
    colour: "red",
    leave_type: "paid",
    accrual_method: "unlimited",
    amount_value: null,
    granting_frequency: null,
    accrual_day: null,
    anniversary_years: null,
    new_hire_rule: "waiting_period",
    waiting_period_value: 3,
    waiting_period_unit: "month",
    carryover_limit_enabled: false,
    carryover_max_days: null,
    carryover_expiration_value: null,
    carryover_expiration_unit: null,
    is_active: true,
    sort_order: 2,
  },
  {
    name: "Loyalty vacation 👑",
    emoji: null,
    colour: "orange",
    leave_type: "paid",
    accrual_method: "anniversary",
    amount_value: 1,
    granting_frequency: null,
    accrual_day: null,
    anniversary_years: 1,
    new_hire_rule: "immediate",
    waiting_period_value: null,
    waiting_period_unit: null,
    carryover_limit_enabled: true,
    carryover_max_days: null,
    carryover_expiration_value: null,
    carryover_expiration_unit: "year",
    is_active: true,
    sort_order: 3,
  },
  {
    name: "Unpaid leave 💸",
    emoji: null,
    colour: "gray",
    leave_type: "unpaid",
    accrual_method: "unlimited",
    amount_value: null,
    granting_frequency: null,
    accrual_day: null,
    anniversary_years: null,
    new_hire_rule: "immediate",
    waiting_period_value: null,
    waiting_period_unit: null,
    carryover_limit_enabled: false,
    carryover_max_days: null,
    carryover_expiration_value: null,
    carryover_expiration_unit: null,
    is_active: true,
    sort_order: 4,
  },
] as const

export async function seedDefaultCategories(workspaceId: string) {
  const rows = DEFAULT_CATEGORIES.map((category) => ({
    ...category,
    workspace_id: workspaceId,
  }))

  const { error } = await supabase.from("time_off_categories").insert(rows)

  if (error) {
    console.warn("Failed to seed default time-off categories:", error.message)
  }
}
